spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:stock_trading;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
